### ISSUE TITLE
Export Log returns error

### ISSUE THREAD

**Issue by pellett655** [tokafew420/MDbScriptTool#10]
When exporting the SQL log, nothing is generated and I see the following error message in debug.log

**[1026/170420.307:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'unshift' of undefined", source: fs://c//UPGRADE/TOOLS/MDbScriptTool-x64-v0.8.0/Scripts/app.min.js (1)**

**Comment by tokafew420** [comment]
Thanks for the issue report. Can you tell which export function you are using? Is it:
- Export button on top toolbar?
- Export button on resultset panel?
- Export from right click menu?

I believe this is because there's an empty resultset so another question is "are there any results?"

Since you are the first person to open an issue, you're also the first person I know of (other than myself and a few colleagues) that uses this tool. Thanks for that. I welcome any feedback that you may have.

**Comment by pellett655** [comment]
Export on the toolbar.  You are correct.  There was no output and that is the reason I was getting the error.  What I was hoping to export was the SQL output messages like rows affected and print statements.

Love the program.  I use it for running 1 command against multiple SQL databases and it seems to work great!  

The only suggestion I have is to condense the application into 1 exe or a smaller footprint to make the application more portable.  It's a lot of files to be transferring back and forth when I'm working in other environments.

**Comment by tokafew420** [comment]
Thanks for your kind words. It gives me motivation to continue the development of this tool (not only for my personal use).

As for the export issue, it's a simple fix and I'll commit a fix soon. Most likely this weekend.

Regarding the size of the project, yes it's unfortunate and the biggest offender is the CefSharp library I'm leveraging. I've looked into several ways of reducing the size of the final deliverable but haven't yet found a viable solution. This tool still has a long way to go before it's considered stable.

Again thanks for the feedback and feel free to throw more feedback this way anytime.
